# Generated by Django 4.1 on 2024-02-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.TextField()),
                ("is_attending", models.BooleanField(default=None)),
                ("number_of_guests", models.IntegerField(default=0)),
                ("meal", models.TextField(blank=True)),
                ("song_1", models.TextField(blank=True)),
                ("song_2", models.TextField(blank=True)),
                ("song_3", models.TextField(blank=True)),
            ],
        ),
    ]
