# Generated by Django 5.0.2 on 2024-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guests",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.TextField()),
                ("is_attending", models.BooleanField(default=None)),
                ("attending_standesamt", models.BooleanField(default=None)),
                ("meal", models.TextField(blank=True)),
                ("song_1", models.TextField(blank=True)),
                ("song_2", models.TextField(blank=True)),
                ("song_3", models.TextField(blank=True)),
            ],
        ),
    ]
