# Generated by Django 4.1 on 2024-02-02 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wedding", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Party",
            new_name="Guests",
        ),
    ]
